services:
  team-plus:
    container_name: team-plus
    image: team-plus:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
